import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { z } from "zod";
import {
  createErrorEnvelope,
  createSuccessEnvelope,
  toHostResponse,
} from "../../src/mcp-server/envelope.js";
import { createAgentServer } from "../../src/mcp-server/index.js";
import { resolveAgentProjectRoot } from "../../src/mcp-server/project-root.js";
import {
  HostSessionSamplingProvider,
  SamplingUnavailableError,
} from "../../src/mcp-server/providers/sampling.js";
import {
  coreTools,
  resolveTimeoutSeconds,
  resolveToolSelection,
  standardTools,
} from "../../src/mcp-server/tool-loader.js";
import { lookupTool, toolRegistry } from "../../src/mcp-server/tool-registry.js";

describe("mcp server", () => {
  it("resolves tool modes and custom lists", () => {
    const available = Object.keys(toolRegistry);

    expect(resolveToolSelection(undefined, available).tools).toEqual([...coreTools]);
    expect(resolveToolSelection("STANDARD", available).tools).toEqual([...standardTools]);
    expect(resolveToolSelection("list,show,unknown", available)).toMatchObject({
      mode: "custom",
      tools: ["list", "get-task"],
    });
    expect(resolveToolSelection("", available).tools).toEqual([...coreTools]);
  });

  it("bounds timeout configuration", () => {
    expect(resolveTimeoutSeconds(undefined)).toBe(60);
    expect(resolveTimeoutSeconds(0)).toBe(1);
    expect(resolveTimeoutSeconds(5000)).toBe(3600);
  });

  it("wraps success and error envelopes for host content", () => {
    expect(toHostResponse(createSuccessEnvelope({ ok: true })).content[0].text).toContain(
      '"success": true',
    );
    expect(toHostResponse(createErrorEnvelope(new Error("bad")))).toMatchObject({
      isError: true,
      error: { message: "bad" },
    });
  });

  it("resolves absolute project roots from env, args, session, and file URIs", () => {
    expect(resolveAgentProjectRoot({ env: { IMPERIAL_PROJECT_ROOT: "/tmp/project" } })).toBe(
      "/tmp/project",
    );
    expect(resolveAgentProjectRoot({ args: { projectRoot: "file:///tmp/project" } })).toBe(
      "/tmp/project",
    );
    expect(resolveAgentProjectRoot({ sessionRoot: "/tmp/session" })).toBe("/tmp/session");
    expect(() => resolveAgentProjectRoot({ args: { projectRoot: "relative" } })).toThrow(
      /absolute/,
    );
  });

  it("creates server startup config and exposes tool registry entries", async () => {
    await expect(createAgentServer({ toolMode: "core", timeoutSeconds: 5 })).resolves.toMatchObject(
      {
        timeoutSeconds: 5,
        tools: [...coreTools],
      },
    );
    expect(lookupTool("get_task")?.name).toBe("get-task");
    expect(toolRegistry["parse-spec"].destructive).toBe(true);
  });

  it("exposes late-phase CLI commands through agent tools", () => {
    for (const name of [
      "prd",
      "check-spec",
      "autopilot",
      "loop",
      "board",
      "roadmap",
      "watch",
      "sync",
      "notifications",
      "history",
      "undo",
      "search",
      "export",
    ]) {
      expect(toolRegistry[name], name).toBeDefined();
    }

    expect(resolveToolSelection("login,find,repl", Object.keys(toolRegistry)).tools).toEqual([
      "auth-login",
      "search",
      "tui",
    ]);
  });

  it("uses host-session sampling for AI-backed agent tools", async () => {
    const root = await mkdtemp(join(tmpdir(), "imperial-mcp-sampling-"));
    const storePath = join(root, "tasks.json");
    const specPath = join(root, "spec.md");
    await writeFile(specPath, "# Spec\n\nBuild useful tools.", "utf8");

    const context = {
      projectRoot: root,
      samplingClient: {
        supportsSampling: true,
        sampleText: async (prompt: string) => {
          if (prompt.includes("Create one implementation task")) {
            return JSON.stringify({
              title: "Sampled task",
              description: "Generated by host sampling",
              details: "Use host inference",
              testStrategy: "Check created task",
              priority: "high",
              dependencies: [],
            });
          }
          if (prompt.includes("Score this product specification")) {
            return JSON.stringify({
              scores: {
                clarity: 8,
                completeness: 8,
                scopedness: 8,
                testability: 8,
                structure: 8,
              },
              overall: 8,
              verdict: "pass",
              gaps: [],
            });
          }
          if (prompt.includes("Assess this implementation task")) {
            return JSON.stringify({
              priority: "high",
              complexityScore: 6,
              recommendedSubtasks: 3,
              reasoning: "Sampled assessment",
            });
          }
          return "Host sampled research";
        },
      },
    };

    const created = await toolRegistry["add-task"].handler(
      { file: storePath, prompt: "Create a task", tag: "master" },
      context,
    );
    expect(created.content[0].text).toContain('"success": true');
    await expect(readFile(storePath, "utf8")).resolves.toContain("Sampled task");

    const research = await toolRegistry.research.handler(
      { file: storePath, query: "What next?" },
      context,
    );
    expect(research.content[0].text).toContain("Host sampled research");

    const check = await toolRegistry["check-spec"].handler({ input: specPath }, context);
    expect(check.content[0].text).toContain("Overall: 8/10");
  });
});

describe("host-session sampling provider", () => {
  it("generates text and structured output through a sampling client", async () => {
    const provider = new HostSessionSamplingProvider({
      supportsSampling: true,
      sampleText: async (prompt) => (prompt === "json" ? '{"title":"Task"}' : "text"),
    });

    await expect(provider.generateText("hello")).resolves.toBe("text");
    await expect(provider.generateObject("json", z.object({ title: z.string() }))).resolves.toEqual(
      {
        title: "Task",
      },
    );
    expect(provider.keyStatus()).toEqual({ ok: true, source: "not-required" });
  });

  it("fails clearly when sampling is unavailable", async () => {
    const provider = new HostSessionSamplingProvider({ supportsSampling: false });
    await expect(provider.generateText("hello")).rejects.toThrow(SamplingUnavailableError);
  });
});
